<?php
/**
 * Layout for printable documents: inspection reports, work order sheets,
 * label runs. No navigation, a letterhead, and a "print" button that hides
 * itself on paper.
 *
 * Variables: $title, $content, $docTitle, $printMeta, $bodyClass, $autoPrint
 */

use App\Dates;
use App\Settings;

$title     = $title     ?? 'Print';
$docTitle  = $docTitle  ?? $title;
$printMeta = $printMeta ?? [];
$bodyClass = $bodyClass ?? '';
$autoPrint = $autoPrint ?? false;
$siteName  = Settings::siteName();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title><?= e($docTitle . ' · ' . $siteName) ?></title>
<link rel="icon" type="image/svg+xml" href="<?= e(asset_url('assets/img/favicon.svg')) ?>">
<link rel="stylesheet" href="<?= e(asset_url('assets/css/app.css')) ?>">
<link rel="stylesheet" href="<?= e(asset_url('assets/css/print.css')) ?>">
<script src="<?= e(asset_url('assets/js/theme-init.js')) ?>"></script>
</head>
<body class="<?= e(trim('print-page ' . $bodyClass)) ?>"<?= $autoPrint ? ' data-auto-print' : '' ?>>

<div class="app-content" style="max-width:1000px;margin:0 auto;">

    <div class="no-print flex items-center justify-between gap-3 mb-5">
        <a class="btn btn-secondary btn-sm" href="javascript:history.back()">
            <?= icon('arrow-left', '', 16) ?> Back
        </a>
        <button type="button" class="btn btn-primary btn-sm" data-print>
            <?= icon('printer', '', 16) ?> Print
        </button>
    </div>

    <div class="print-letterhead print-only">
        <div class="flex items-center gap-3">
            <span class="brand-mark" aria-hidden="true">
                <?php if (Settings::logoUrl() !== null): ?>
                    <img src="<?= e((string) Settings::logoUrl()) ?>" alt="">
                <?php else: ?>
                    <?php require APP_ROOT . '/assets/img/logo.svg'; ?>
                <?php endif; ?>
            </span>
            <div>
                <p class="org-name"><?= e(Settings::organizationName()) ?></p>
                <p class="doc-title"><?= e($docTitle) ?></p>
            </div>
        </div>
        <div class="print-meta">
            <?php foreach ($printMeta as $label => $value): ?>
                <div><strong><?= e($label) ?>:</strong> <?= e($value) ?></div>
            <?php endforeach; ?>
            <div>Printed <?= e(Dates::datetime(Dates::nowUtc())) ?></div>
        </div>
    </div>

    <?= $content ?? '' ?>

    <div class="print-footer print-only">
        Generated by RideLog for <?= e(Settings::organizationName()) ?>.
        This document is a record of maintenance activity and should be retained
        according to your operating procedures.
    </div>
</div>

<script src="<?= e(asset_url('assets/js/core.js')) ?>" defer></script>
<script src="<?= e(asset_url('assets/js/print.js')) ?>" defer></script>
</body>
</html>
